project_id = "kuoxpuxrmecjczqbvwsk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[edge_runtime]
enabled = true
port = 54326

[analytics]
enabled = false
port = 54327

[functions.get-weather]
verify_jwt = false