name: Sync Personal Repo to Church Repo

on:
  workflow_dispatch: # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout church repo (target) with CHURCH_PAT
    - name: Checkout church repo
      uses: actions/checkout@v3
      with:
        repository: tacnwmedia/spirit-stream-live
        token: ${{ secrets.CHURCH_PAT }}

    # 2. Configure Git
    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    # 3. Set up SSH key for personal repo
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PERSONAL_REPO_TOKEN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # 4. Add personal repo as SSH remote and fetch
    - name: Add personal repo as remote
      run: |
        git remote add personal git@github.com:Akin-og/spirit-stream-live.git
        git fetch personal main

    # 5. Backup current main branch of church repo
    - name: Backup church repo main branch
      run: |
        backup_branch="backup-main-$(date +%Y%m%d%H%M%S)"
        git branch $backup_branch
        git push origin $backup_branch

    # 6. Merge personal repo into church repo
    - name: Merge personal repo main into church repo
      run: |
        git checkout main
        git merge personal/main --allow-unrelated-histories -m "Sync from personal repo"

    # 7. Push changes to church repo
    - name: Push changes to church repo
      run: git push origin main
